# deploy new release of a catchpy server
---


- hosts: catchpy
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
    - vars/catchpy_vars.yml

  handlers:
    - include: handlers/handlers.yml

  roles:
    - webapp_deploy
    - { role: webapp_config, when: update_configs is defined and update_configs == True}

- hosts: catchpy
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
    - vars/catchpy_vars.yml

  handlers:
    - include: handlers/handlers.yml

  roles:
    # have to set this as a separate list of roles because of handlers
    # that need to run after a deploy/config block
    - webapp_check_deploy

