---

    - name: create policy for ec2 to cloudwatch
      become: no
      local_action:
        module: iam_managed_policy
        policy: "{{ lookup('file', '../files/cloudwatch_put_metric_policy.json') }}"
        policy_description: "allow ec2 to put metric data into cloudwatch"
        policy_name: "put_metric_in_cloudwatch_role"
        state: present
      register: policy_result
      ignore_errors: yes

    - debug:
        var: policy_result

    - name: create role for instance profile
      become: no
      local_action:
        module: iam
        iam_type: role
        name: "cloudwatch_put_metric_role"
        trust_policy: "{{ lookup('file', '../files/cloudwatch_put_metric_policy.json') }}"
        state: present
        #trust_policy:
        #  Version: '2012-10-17'
        #  Statement:
        #  - Action:
        #    - cloudwatch:putMetricData
        #    - cloudwatch:getMetricData
        #    - cloudwatch:listMetrics
        #    Effect: Allow
        #    Resource: '*'
        #  state: present
